<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<OutputType>Library</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\kat_mob_soft.Domain\TravelAgency.Domain.csproj" />
		<ProjectReference Include="..\kat_mob_soft.Service\TravelAgency.Service.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="6.0.0" />
	</ItemGroup>

</Project>